version: "3.1"
services:
    www:
        build: ./
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: user
            DATABASE_PASSWORD : 123456
            MYSQL_ROOT_PASSWORD : 123456
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8003:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: 5fsnO
            MYSQL_ROOT_PASSWORD: 5fsnO
        networks:
            - default
 
    
volumes:
    persistent:
        

